name: Build Android APK
on:
  push:
    branches: [ main ] # سيتم البناء عند كل تحديث للكود

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Flet and Dependencies
        run: |
          pip install flet requests

      - name: Build APK
        run: |
          # هذا الأمر يحول الكود إلى تطبيق أندرويد
          flet build apk --project "LordApp"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/apk/*.apk
